In [27]:
import numpy as np

In [28]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2D10 = mat2D * 10

In [29]:
print(f"Matriks 1D :\n {mat1D}")
print(f"Matriks 1D indeks ke 7 : {mat1D[7]}")
print(f"Matriks 1D * 10 : {mat1D * 10}")


Matriks 1D :
 [1 2 3 4 5 6 7 8 9]
Matriks 1D indeks ke 7 : 8
Matriks 1D * 10 : [10 20 30 40 50 60 70 80 90]


In [30]:
print(f"Matriks 2D:\n{mat2D}")
print(f"Matriks 2D * 10 :\n{mat2D*10}")
print(mat2D10[0])
print(mat2D10[0][2])

Matriks 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks 2D * 10 :
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10 20 30]
30


In [31]:
print(mat1D.shape)
print(mat2D.shape)

(9,)
(3, 3)


In [32]:
print(f"ukuran dari mat1D :{mat1D.size}")
print(f"ukuran dari mat2D :{mat2D.size}")


ukuran dari mat1D :9
ukuran dari mat2D :9


In [33]:
print(f"ukuran dari mat1D:{mat1D.size}")
print(f"ukuran dari mat2D:{mat2D.size}")


ukuran dari mat1D:9
ukuran dari mat2D:9


In [40]:
#spesial matriks
mZero = np.zeros((3,3))
mOne = np.ones ((3,3))
mFull = np.full ((4,4),7)
mIdentity = np.eye((4))
mFRandom1D = np.random.rand(5)
mFRandom2D = np.random.rand(3,3)
mIRandom1D = np.random.randint(10,100, size=5)
mIRandom2D = np.random.randint(10,100, size=(4,4))
#membuat array ukuran 4*4 diisi dengan nilai 7
print(f"Matriks mZero :\n{mZero}")
print(f"Matriks mOne :\n{mOne}")
print(f"Matriks mFull :\n{mFull}")
print(f"Matriks mIdentity :\n{mIdentity}")
print(f"Matriks mFRandom1D :\n{mFRandom1D}")
print(f"Matriks mFRandom2D :\n{mFRandom2D}")
print(f"Matriks mIRandom1D :\n{mFRandom1D}")
print(f"Matriks mIRandom2D :\n{mFRandom2D}")


Matriks mZero :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriks mOne :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matriks mFull :
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Matriks mIdentity :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriks mFRandom1D :
[0.22956785 0.80972389 0.00445203 0.73356277 0.33208563]
Matriks mFRandom2D :
[[0.51879019 0.92777588 0.33102488]
 [0.46729997 0.85590283 0.19268131]
 [0.0439993  0.51959988 0.33785166]]
Matriks mIRandom1D :
[0.22956785 0.80972389 0.00445203 0.73356277 0.33208563]
Matriks mIRandom2D :
[[0.51879019 0.92777588 0.33102488]
 [0.46729997 0.85590283 0.19268131]
 [0.0439993  0.51959988 0.33785166]]


In [43]:
#mengubah bentuk array
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
mShape = data.reshape((9,1))
mFlat = data.flatten()

print(f"Matriks data :\n{data}")
print(f"Matriks mShape :\n{mShape}")
print(f"Matriks mFlat :\n{mFlat}")

Matriks data :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks mShape :
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Matriks mFlat :
[1 2 3 4 5 6 7 8 9]


In [44]:
#Deskriptif statistik
x = np.array([1,2,3,4])
y = np.array ([2,5,7,9])

#menghitung dot product
r1 = np.dot(x,y)
r2 = np.dot(x,y)
print(f"hasil dari dot product :{r1}")
print(f"haisl penjumlahan matriks :/n{r2}")
print(f"nilai minimum : {y.min()}")
print(F"nilai maksimum :{y.max()}")
print(F"nilai rata - rata : {y.mean()}")
print(F"nilai total : {y.sum()}")
print(F"nilai deviasi : {y.std()}")


hasil dari dot product :69
haisl penjumlahan matriks :/n69
nilai minimum : 2
nilai maksimum :9
nilai rata - rata : 5.75
nilai total : 23
nilai deviasi : 2.5860201081971503


In [53]:
#filtering
nilaiPemrograman = np.array([100,90,100,80,50,50,50,40])

#tampilkan nilai pemrograman yang lebih dari 50 -> LULUS
jmlLulus = nilaiPemrograman[nilaiPemrograman>50]
print(jmlLulus)
print(f"Mahasiswa yang lulus sebanyak : {jmlLulus.size}")
print(f"Mahasiswa yang tidak lulus : {nilaiPemrograman.size - jmlLulus.size}")


[100  90 100  80]
Mahasiswa yang lulus sebanyak : 4
Mahasiswa yang tidak lulus : 4


<b>Project Generate Data</b><br>
Buatlah 100 Data Custome CC, yang akan digunakan untuk prediksi atau klasifikasi yaitu:
<ol> 
    <li>Usia : 17 -60 </li>
    <li>Gender: L/P </li>
    <li>Transaksi : perBulan : 0 -50 </li>
    <li>pembayaran : Buruk, Sedang, Bagus </li>
    
</ol>

In [70]:
import numpy as np
import pandas as pd

jmlData = 100
usia = np.random.randint(17,61,size=jmlData)
gender = np.random.choice(['L','P'],size=jmlData)
transaksi = np.random.randint(0,51, size=jmlData)
pembayaran = np.random.choice(['buruk','sedang','bagus'],size=jmlData)

df = pd.DataFrame({
    'usia' :usia,
    'gender':gender,
    'transaksi':transaksi,
    'pembayaran':pembayaran
})
print (df)
print (df.info()) #menampilkan karakteristik data
print (df.head()) #menampilkan isi tabel 5 baris pertama

#tampilkan usia yang paling muda
print(f"usia customer termuda:{df['usia'].min()}")
print(f"usia customer tertua :{df['usia'].max()}")

#tampilkan customer laki laki 
jmlL = df[df['gender']=='L']
print(f"jumlah customer Laki-Laki: {jmlL.size/4}")
print(f"jumlah customer Laki-Laki :{jmlL['gender'].size}")
      
df.to_csv("dataCustomer.csv")

    usia gender  transaksi pembayaran
0     44      P          3      buruk
1     43      L         20      buruk
2     41      L          9      buruk
3     53      L         13      bagus
4     18      L         22     sedang
..   ...    ...        ...        ...
95    54      L          3      buruk
96    28      L          4     sedang
97    49      P         39     sedang
98    27      L         20      buruk
99    34      P         19      buruk

[100 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   usia        100 non-null    int32 
 1   gender      100 non-null    object
 2   transaksi   100 non-null    int32 
 3   pembayaran  100 non-null    object
dtypes: int32(2), object(2)
memory usage: 2.5+ KB
None
   usia gender  transaksi pembayaran
0    44      P          3      buruk
1    43      L         20      buruk
2    41    